* member

** visibilitiy

repository should have a 4-tier visibility system:

+ public: everyone, including guests, can see & http clone.
  + archived: public. everyone can see & http clone. ssh push is not allowed.
+ internal: whoever has an account and logged in can see. no one can http clone.
+ limited: whoever is a member of residing namespace or the repo can see. no one can http clone. available only when namespaces are enabled.
+ private: whoever is a member of the repo can see. no one can http clone.

namespace should have a 3-tier visibility system:

+ public: everyone, including guests, can see.
  + internal: whoever has an account and logged in can see.
+ private: whoever is a member can see.

"is a member" is defined to be any of the following situation:

+ is an admin or super admin;
+ is the repo/namespace's owner;
+ listed in the repo/namespace's acl.

membership of a namespace does not imply the membership of the repositories within. if a repository has been set to private and a user is set in namespace acl but not the acl of that repository, that user is not seen as a member of that repository and is thus unable to see the repository.

  
